# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'RMPM(afc11291-9826-46be-b852-70349146ddf8)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo $servicePrincipalId | rev'
    addSpnToEnvironment: true


